### PR TITLE
Require a special permission for clobbering.

### PR DESCRIPTION
**Pull request by mrrrgn**

### CODE REVIEW

**Comment by djmitche** [comment]
This bit looks good -- the other methods are informational, so they don't need auth.

I can't quite piece together what route the buildslaves use, but that's probably due to under-caffeination..

**Comment by Callek** [comment]
...still failing

**Comment by mrrrgn** [comment]
@Callek At last!

**Comment by Callek** [comment]
:+1: looking through this, I'm satisfied, but I am not a huge fan of the perm name (though I can't think of any better naming), 

AND I'd love if the test_context didn't always have that perm, and instead only added the perm for the tests that need it (and have tests that the perm itself is required to use those endpoints).

That way you ensure the no-perm-needed endpoints stay no-perm-needed (until you conciously decide they need a perm) and you get tests that the perm-needed-ones stay perm needed, also explicitly.

I'm ok if thats a followup.

**Comment by mrrrgn** [comment]
Fair, I'll change the perm name to clobberer.post.clobber and modify the test context.

**Comment by mrrrgn** [comment]
I'm going to need to come back to the test context later. It's giving me troubles that I fear may become a rabbit hole.

**Pull request merged**
